version: "3"

volumes:
  influxdb_:
  telegraf_:

services:
  # Define a Telegraf service
  telegraf:
    image: ${REGISTRY}/telegraf:latest
    container_name: $COMPOSE_PROJECT_NAME.telegraf
    build: ./images/telegraf
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - tier_log
  # Define an InfluxDB service
  influxdb:
    container_name: $COMPOSE_PROJECT_NAME.influxdb
    image: influxdb:1.3-alpine
    volumes:
      - influxdb_:/var/lib/influxdb
    networks:
      - tier_log
  # Define a Chronograf service
  chronograf:
    image: ${REGISTRY}/chronograf:latest
    container_name: $COMPOSE_PROJECT_NAME.chronograf
    image: chronograf:1.3-alpine
    restart: unless-stopped
    env_file:
      - ./.env.chronograf
    networks:
      - tier_log
      - tier_1
  # Define a Kapacitor service
  kapacitor:
    container_name: $COMPOSE_PROJECT_NAME.kapacitor
    image: kapacitor:1.3-alpine
    restart: unless-stopped
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    networks:
      - tier_log
